In [6]:
import pandas as pd
import numpy as np

In [125]:
df = pd.read_csv(r"/data/insurance.csv")
df.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [11]:
target = "charges"
y = np.log(df[target])
X = df.drop(columns=[target])

X = pd.get_dummies(X)
X

age     bmi  children  gender_female  gender_male  smoker_no  \
0      19  27.900         0              1            0          0   
1      18  33.770         1              0            1          1   
2      28  33.000         3              0            1          1   
3      33  22.705         0              0            1          1   
4      32  28.880         0              0            1          1   
5      31  25.740         0              1            0          1   
6      46  33.440         1              1            0          1   
7      37  27.740         3              1            0          1   
8      37  29.830         2              0            1          1   
9      60  25.840         0              1            0          1   
10     25  26.220         0              0            1          1   
11     62  26.290         0              1            0          0   
12     23  34.400         0              0            1          1   
13     56  39.820         0              1            0          1   
14     27  42.130         0              0            1          0   
15     19  24.600         1              0            1          1   
16     52  30.780         1              1            0          1   
17     23  23.845         0              0            1          1   
18     56  40.300         0              0            1          1   
19     30  35.300         0              0            1          0   
20     60  36.005         0              1            0          1   
21     30  32.400         1              1            0          1   
22     18  34.100         0              0            1          1   
23     34  31.920         1              1            0          0   
24     37  28.025         2              0            1          1   
25     59  27.720         3              1            0          1   
26     63  23.085         0              1            0          1   
27     55  32.775         2              1            0          1   
28     23  17.385         1              0            1          1   
29     31  36.300         2              0            1          0   
...   ...     ...       ...            ...          ...        ...   
1308   25  30.200         0              1            0          0   
1309   41  32.200         2              0            1          1   
1310   42  26.315         1              0            1          1   
1311   33  26.695         0              1            0          1   
1312   34  42.900         1              0            1          1   
1313   19  34.700         2              1            0          0   
1314   30  23.655         3              1            0          0   
1315   18  28.310         1              0            1          1   
1316   19  20.600         0              1            0          1   
1317   18  53.130         0              0            1          1   
1318   35  39.710         4              0            1          1   
1319   39  26.315         2              1            0          1   
1320   31  31.065         3              0            1          1   
1321   62  26.695         0              0            1          0   
1322   62  38.830         0              0            1          1   
1323   42  40.370         2              1            0          0   
1324   31  25.935         1              0            1          1   
1325   61  33.535         0              0            1          1   
1326   42  32.870         0              1            0          1   
1327   51  30.030         1              0            1          1   
1328   23  24.225         2              1            0          1   
1329   52  38.600         2              0            1          1   
1330   57  25.740         2              1            0          1   
1331   23  33.400         0              1            0          1   
1332   52  44.700         3              1            0          1   
1333   50  30.97

In [13]:
X.describe()

age          bmi     children  gender_female  gender_male  \
count  1338.000000  1338.000000  1338.000000    1338.000000  1338.000000   
mean     39.207025    30.663397     1.094918       0.494768     0.505232   
std      14.049960     6.098187     1.205493       0.500160     0.500160   
min      18.000000    15.960000     0.000000       0.000000     0.000000   
25%      27.000000    26.296250     0.000000       0.000000     0.000000   
50%      39.000000    30.400000     1.000000       0.000000     1.000000   
75%      51.000000    34.693750     2.000000       1.000000     1.000000   
max      64.000000    53.130000     5.000000       1.000000     1.000000   

         smoker_no   smoker_yes  region_northeast  region_northwest  \
count  1338.000000  1338.000000       1338.000000       1338.000000   
mean      0.795217     0.204783          0.242152          0.242900   
std       0.403694     0.403694          0.428546          0.428995   
min       0.000000     0.000000          0.000000          0.000000   
25%       1.000000     0.000000          0.000000          0.000000   
50%       1.000000     0.000000          0.000000          0.000000   
75%       1.000000     0.000000          0.000000          0.000000   
max       1.000000     1.000000          1.000000          1.000000   

       region_southeast  region_southwest  
count       1338.000000       1338.000000  
mean           0.272048          0.242900  
std            0.445181          0.428995  
min            0.000000          0.000000  
25%            0.000000          0.000000  
50%            0.000000          0.000000  
75%            1.000000          0.000000  
max            1.000000          1.000000

In [17]:
type(X.values)

numpy.ndarray

In [18]:
a = X.values

In [20]:
a.astype("float32").dtype

dtype('float32')

In [60]:
np.random.seed(1)
np.random.randint(0, 100, 3)

array([37, 12, 72])

In [14]:
from sklearn import model_selection

In [61]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X.values, y.values
                , test_size = 0.3, random_state = 1)

In [62]:
X_train

array([[50.  , 26.41,  0.  , ...,  1.  ,  0.  ,  0.  ],
       [21.  , 26.4 ,  1.  , ...,  0.  ,  0.  ,  1.  ],
       [25.  , 26.22,  0.  , ...,  0.  ,  0.  ,  0.  ],
       ...,
       [51.  , 34.96,  2.  , ...,  0.  ,  0.  ,  0.  ],
       [40.  , 22.22,  2.  , ...,  0.  ,  1.  ,  0.  ],
       [57.  , 27.94,  1.  , ...,  0.  ,  1.  ,  0.  ]])

In [63]:
a = np.array([3, 7, 0, 3, 10])

In [64]:
np.mean(a)

4.6

In [65]:
a2 = a - 4.6
a2

array([-1.6,  2.4, -4.6, -1.6,  5.4])

In [66]:
np.mean(a2)

3.552713678800501e-16

In [72]:
np.sum(a2)

1.7763568394002505e-15

In [71]:
0.2 - 0.3

-0.09999999999999998

In [73]:
np.std(a)

3.49857113690718

In [75]:
a3 = a2/np.std(a)

In [76]:
np.mean(a3)

8.881784197001253e-17

In [77]:
np.std(a3)

1.0

In [78]:
from sklearn import preprocessing

In [79]:
scaler = preprocessing.StandardScaler()

In [80]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [81]:
scaler.mean_

array([38.82264957, 30.68218483,  1.10470085,  0.48824786,  0.51175214,
        0.79380342,  0.20619658,  0.24038462,  0.23824786,  0.26495726,
        0.25641026])

In [83]:
pd.DataFrame(X_train).describe()

0           1           2           3           4           5   \
count  936.000000  936.000000  936.000000  936.000000  936.000000  936.000000   
mean    38.822650   30.682185    1.104701    0.488248    0.511752    0.793803   
std     14.029097    6.087997    1.222664    0.500129    0.500129    0.404790   
min     18.000000   15.960000    0.000000    0.000000    0.000000    0.000000   
25%     26.000000   26.272500    0.000000    0.000000    0.000000    1.000000   
50%     38.000000   30.495000    1.000000    0.000000    1.000000    1.000000   
75%     51.000000   34.717500    2.000000    1.000000    1.000000    1.000000   
max     64.000000   53.130000    5.000000    1.000000    1.000000    1.000000   

               6           7           8           9           10  
count  936.000000  936.000000  936.000000  936.000000  936.000000  
mean     0.206197    0.240385    0.238248    0.264957    0.256410  
std      0.404790    0.427545    0.426239    0.441546    0.436884  
min      0.000000    0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000    0.000000    0.000000  
75%      0.000000    0.000000    0.000000    1.000000    1.000000  
max      1.000000    1.000000    1.000000    1.000000    1.000000

In [84]:
scaler.scale_

array([14.02160116,  6.08474408,  1.22201114,  0.49986187,  0.49986187,
        0.4045733 ,  0.4045733 ,  0.42731704,  0.42601152,  0.44131045,
        0.43665093])

In [85]:
X_train_std = scaler.transform(X_train)

In [86]:
X_test_std = scaler.transform(X_test)

In [87]:
from sklearn import linear_model

In [88]:
est = linear_model.LinearRegression()

In [89]:
est.fit(X_train_std, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [92]:
y_test_pred = est.predict(X_test_std)

In [95]:
result = pd.DataFrame({"actual": y_test, "prediction": y_test_pred})
result["error"] = result.prediction - result.actual
result.head()

actual  prediction     error
0  7.406364    8.066165  0.659801
1  9.337257    9.289310 -0.047948
2  9.082347    9.075931 -0.006416
3  9.247779    9.347415  0.099637
4  7.651158    7.961673  0.310515

In [97]:
sse = (result.error ** 2).sum()
sse

71.96577026898734

In [104]:
baseline = np.mean(y_test)

In [105]:
sst = ((baseline - y_test) ** 2).sum()

In [106]:
sse/sst

0.21281775110947085

In [107]:
r2 = 1 - sse/sst
r2

0.7871822488905291

In [102]:
from sklearn import metrics

In [103]:
metrics.r2_score(y_test, y_test_pred)

0.7871822488905291

In [108]:
mse = (result.error ** 2).mean()
mse

0.17901932902733184

In [110]:
rmse = mse ** 0.5
rmse

0.42310675842786044

In [127]:
target = "charges"
y = np.log(df[target])
X = df.drop(columns=[target])
X["age_group"] = np.where(df.age > 60, "g1", "g2")
X["bmi_high"] = np.where(df.bmi > 30, 1, 0)

X = pd.get_dummies(X)

X_train, X_test, y_train, y_test = model_selection.train_test_split(X.values, y.values
                , test_size = 0.3, random_state = 1)

poly = preprocessing.PolynomialFeatures(degree=2, include_bias=False)
X_train = poly.fit_transform(X_train) 
X_test = poly.transform(X_test)

scaler = preprocessing.StandardScaler()

X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

est = linear_model.LinearRegression()

est.fit(X_train_std, y_train)


y_train_pred = est.predict(X_train_std)
y_test_pred = est.predict(X_test_std)


print("R2 train: ", metrics.r2_score(y_train, y_train_pred))
print("R2 test: ", metrics.r2_score(y_test, y_test_pred))

print("Rmse train: ", metrics.mean_squared_error(y_train, y_train_pred) ** 0.5)
print("Rmse test: ", metrics.mean_squared_error(y_test, y_test_pred) ** 0.5)

R2 train:  0.8365256762210191
R2 test:  0.8715673233650583
Rmse train:  0.3719862646953874
Rmse test:  0.32868796651232723


In [123]:
df = pd.read_excel("/Users/abasar/Downloads/CCPP/Folds5x2_pp.xlsx", sheet_name=None)
df = pd.concat(df.values())
df.shape

(47840, 5)